In [1]:
import pickle
import pandas as pd

# Load new_df.pkl
path = 'new_df.pkl'
with open(path, 'rb') as f:
    new_df = pickle.load(f)
new_df.head()

,name,date,quantity,exposure,tracked_id,traj,VCL,VAP,VSL,LIN,...,BeatCross,ALH,img,cluster,c6_labels,c6_values,c7_labels,c7_values,c8_labels,c8_values
0,balder,01062021-25,0,0.0,1.0,"[[69, 70, 71, 71, 72, 73, 73, 74, 75, 76, 76, ...",79.959810,65.180660,60.576260,0.757584,...,30.000000,4.276645,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",0,3,0.286927,4,0.471847,6,0.773797
1,balder,01062021-25,0,0.0,3.0,"[[209, 208, 210, 210, 211, 212, 212, 214, 214,...",89.038410,47.606697,44.321228,0.497777,...,44.482758,3.3122602,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",0,4,0.356413,1,0.620499,5,0.673387
2,balder,01062021-25,0,0.0,4.0,"[[166, 166, 166, 166, 166, 166, 165, 165, 164,...",55.782050,39.061245,37.602840,0.674103,...,33.846153,2.2061138,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",4,2,0.350242,4,0.583035,7,0.512272
3,balder,01062021-25,0,0.0,6.0,"[[153, 152, 151, 151, 150, 149, 149, 149, 148,...",61.317635,50.661057,48.099777,0.784436,...,36.585365,3.6620018,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",0,0,0.452616,5,0.458211,0,0.41063
4,balder,01062021-25,0,0.0,7.0,"[[101, 100, 100, 100, 100, 92, 91, 91, 92, 91,...",92.437790,31.140326,24.251595,0.262356,...,21.600000,2.8383772,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...",2,2,0.317309,3,0.398546,7,0.957646

In [2]:
print(len(new_df))

20500

In [3]:
# List of elem in new_df['quantity']
quantity_list = new_df['quantity'].unique().tolist()

# List of elem in new_df['exposure']
exposure_list = new_df['exposure'].unique().tolist()

# List of elem in new_df['c7_labels']
cluster_list = new_df['c7_labels'].unique().tolist()

print(quantity_list)
print(exposure_list)
print(cluster_list)

['0', '1u', '100n', '10n']
[0.0, 30.0]
[4, 1, 5, 3, 2, 6, 0]

In [5]:
import matplotlib.pyplot as plt

# For each elem in cluster_list, quantity_list, and exposure_list, plot the trajectories
for q in quantity_list:
    for c in cluster_list:
        for e in exposure_list:
            title = 'c_' + str(c) + '-' + 'e_' + str(e) + '-' + 'q_' + str(q)
            print(title)
            for index, row in new_df.iterrows():
                if (row['exposure'] == e) & (row['c7_labels'] == c) & (row['quantity'] == q):        
                    x = row['traj'][0]
                    y = row['traj'][1]
                    plt.plot(x, y)
            plt.title(title)
            filename = 'img/' + title + '.png'
            plt.savefig(filename) 
            plt.close("all")

c_4-e_0.0-q_0
c_4-e_30.0-q_0
c_1-e_0.0-q_0
c_1-e_30.0-q_0
c_5-e_0.0-q_0
c_5-e_30.0-q_0
c_3-e_0.0-q_0
c_3-e_30.0-q_0
c_2-e_0.0-q_0
c_2-e_30.0-q_0
c_6-e_0.0-q_0
c_6-e_30.0-q_0
c_0-e_0.0-q_0
c_0-e_30.0-q_0
c_4-e_0.0-q_1u
c_4-e_30.0-q_1u
c_1-e_0.0-q_1u
c_1-e_30.0-q_1u
c_5-e_0.0-q_1u
c_5-e_30.0-q_1u
c_3-e_0.0-q_1u
c_3-e_30.0-q_1u
c_2-e_0.0-q_1u
c_2-e_30.0-q_1u
c_6-e_0.0-q_1u
c_6-e_30.0-q_1u
c_0-e_0.0-q_1u
c_0-e_30.0-q_1u
c_4-e_0.0-q_100n
c_4-e_30.0-q_100n
c_1-e_0.0-q_100n
c_1-e_30.0-q_100n
c_5-e_0.0-q_100n
c_5-e_30.0-q_100n
c_3-e_0.0-q_100n
c_3-e_30.0-q_100n
c_2-e_0.0-q_100n
c_2-e_30.0-q_100n
c_6-e_0.0-q_100n
c_6-e_30.0-q_100n
c_0-e_0.0-q_100n
c_0-e_30.0-q_100n
c_4-e_0.0-q_10n
c_4-e_30.0-q_10n
c_1-e_0.0-q_10n
c_1-e_30.0-q_10n
c_5-e_0.0-q_10n
c_5-e_30.0-q_10n
c_3-e_0.0-q_10n
c_3-e_30.0-q_10n
c_2-e_0.0-q_10n
c_2-e_30.0-q_10n
c_6-e_0.0-q_10n
c_6-e_30.0-q_10n
c_0-e_0.0-q_10n
c_0-e_30.0-q_10n